# Generated by Django 5.1.1 on 2024-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityShortlistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField()),
                ('current_college', models.CharField(max_length=255)),
                ('current_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_budget', models.IntegerField()),
                ('shortlist_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
